name: 'Install Helm releases'
description: 'Deploy a service using Warestack and Helm package manager'
inputs:
  environment:
    description: "The value can be development, staging, production, etc."
    required: true
  release_name:
    description: 'Release name to be used for the helm releases and Container Repository'
    required: true
  namespace:
    description: 'The organization to be used for the namespace in helm install'
    required: true
  registry_url:
    description: 'URL of the container registry'
    required: true
  image_name:
    description: 'Name of the image to build and push'
    required: true
  image_tag:
    description: 'The tag of the image pushed to the container registry'
    required: true
  public_url:
    description: 'Public URL to used for exposing the service'
    required: true
  port:
    description: 'Port to used for exposing the pod in Kube'
    required: true
  helm_path:
    description: 'Path to the Helm chart'
    required: true

runs:
  using: "composite"
  steps:
    # Install or Upgrade the Helm release
    - name: Install or upgrade helm release
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RELEASE_NAME: ${{ inputs.release_name }}
        NAMESPACE: ${{ inputs.namespace }}
        IMAGE_REPO: ${{ inputs.registry_url }}/${{ inputs.image_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        PUBLIC_URL: ${{ inputs.public_url }}
        PORT: ${{ inputs.port }}
        HELM_PATH: ${{ inputs.helm_path }}
      run: |-
        helm upgrade ${{ env.RELEASE_NAME }} ${{ env.HELM_PATH }} --namespace ${{ env.NAMESPACE }} --create-namespace --wait \
          --values ${{ env.HELM_PATH }}/values-${{ env.ENVIRONMENT }}.yaml \
          --set image.repository=$IMAGE_REPO \
          --set image.tag=$IMAGE_TAG \
          --set cert.tls.secretName=$RELEASE_NAME \
          --set cert.commonName=$PUBLIC_URL \
          --set cert.dnsNames.hosts={$PUBLIC_URL} \
          --set service.port=$PORT \
          --set ingress.hosts[0].host=$PUBLIC_URL \
          --set ingress.tls[0].secretName=$RELEASE_NAME \
          --set ingress.tls[0].hosts={$PUBLIC_URL} \
          --install
      shell: bash
