default_stages:
  - commit
  - push

# Configuration for pre-commit hooks
repos:

  # General hooks from the pre-commit-hooks repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        # Removes any trailing whitespace from lines in text files
      - id: trailing-whitespace
        # Ensures files end with a newline
      - id: end-of-file-fixer
        # Checks YAML files for syntax errors
      - id: check-yaml
        # Checks JSON files for syntax errors
      - id: check-json

  # Hooks for linting Markdown files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
        # Ensures consistent style for Markdown files
      - id: markdownlint

  # Hooks for spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
        # Spell checks files, ignoring specific words if needed
      - id: codespell
        args: ['--ignore-words-list=seperated']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
      - id: eslint
        exclude: 'frontend/.*|.eslintrc.js'
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@8.52.0
          - eslint-config-standard@17.1.0
          - eslint-plugin-import@2.29.0
          - eslint-plugin-n@16.2.0
          - eslint-plugin-promise@6.1.1
          - eslint-config-next@13.5.5
